//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BasicAno {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasicAno() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Resources.BasicAno", typeof(BasicAno).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר מכרז.
        /// </summary>
        public static string AUAuctionNumber {
            get {
                return ResourceManager.GetString("AUAuctionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם המכרז.
        /// </summary>
        public static string AUName {
            get {
                return ResourceManager.GetString("AUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטאטוס.
        /// </summary>
        public static string AUStatusID {
            get {
                return ResourceManager.GetString("AUStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מכרז.
        /// </summary>
        public static string CLAuctionID {
            get {
                return ResourceManager.GetString("CLAuctionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר סל.
        /// </summary>
        public static string CLDisplayNumber {
            get {
                return ResourceManager.GetString("CLDisplayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם הסל.
        /// </summary>
        public static string CLName {
            get {
                return ResourceManager.GetString("CLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטאטוס.
        /// </summary>
        public static string CLStatusID {
            get {
                return ResourceManager.GetString("CLStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר ספקים בתיחור.
        /// </summary>
        public static string CLSuppliersInTichur {
            get {
                return ResourceManager.GetString("CLSuppliersInTichur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערך אינו תקין..
        /// </summary>
        public static string CLWro {
            get {
                return ResourceManager.GetString("CLWro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &amp;nbsp;*.
        /// </summary>
        public static string GenError {
            get {
                return ResourceManager.GetString("GenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערך כבר קיים בתוך המסד.
        /// </summary>
        public static string InDatabase {
            get {
                return ResourceManager.GetString("InDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא להכניס 9 ספרות.
        /// </summary>
        public static string InvalidCN {
            get {
                return ResourceManager.GetString("InvalidCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אימייל לא תקין.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; טלפון אינו תקין.
        /// </summary>
        public static string InvalidPN {
            get {
                return ResourceManager.GetString("InvalidPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד מרכב&quot;ה אינו לפי תבנית.
        /// </summary>
        public static string NotMarkevaFit {
            get {
                return ResourceManager.GetString("NotMarkevaFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המספר אינו בטווח בין 1 ל 999.
        /// </summary>
        public static string NotThrDig {
            get {
                return ResourceManager.GetString("NotThrDig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערך אינו ת&quot;ז תקינה.
        /// </summary>
        public static string notValidId {
            get {
                return ResourceManager.GetString("notValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המספר הנ&quot;ל קטן שווה לאפס.
        /// </summary>
        public static string NotZEPDig {
            get {
                return ResourceManager.GetString("NotZEPDig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערך חייב ליהיות ביטוי מספרי.
        /// </summary>
        public static string numberExpe {
            get {
                return ResourceManager.GetString("numberExpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערך הניתן אינו מתאים לדפוס.
        /// </summary>
        public static string patrNotMa {
            get {
                return ResourceManager.GetString("patrNotMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השדה {0} נדרש, אנא מלא אותו.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; טלפון.
        /// </summary>
        public static string SUPANumberID {
            get {
                return ResourceManager.GetString("SUPANumberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; מכרז.
        /// </summary>
        public static string SUPAuctionID {
            get {
                return ResourceManager.GetString("SUPAuctionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ח.פ..
        /// </summary>
        public static string SUPCompanyNumber {
            get {
                return ResourceManager.GetString("SUPCompanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם איש קשר.
        /// </summary>
        public static string SUPContactName {
            get {
                return ResourceManager.GetString("SUPContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אימייל.
        /// </summary>
        public static string SUPEmail {
            get {
                return ResourceManager.GetString("SUPEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם הספק.
        /// </summary>
        public static string SUPName {
            get {
                return ResourceManager.GetString("SUPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קידומת.
        /// </summary>
        public static string SUPPrefixID {
            get {
                return ResourceManager.GetString("SUPPrefixID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטאטוס.
        /// </summary>
        public static string SUPStatusID {
            get {
                return ResourceManager.GetString("SUPStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד מרכב&quot;ה.
        /// </summary>
        public static string UNIMerkavaID {
            get {
                return ResourceManager.GetString("UNIMerkavaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם יחידה.
        /// </summary>
        public static string UNIName {
            get {
                return ResourceManager.GetString("UNIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטאטוס.
        /// </summary>
        public static string UNIStatusID {
            get {
                return ResourceManager.GetString("UNIStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אימייל.
        /// </summary>
        public static string USEmail {
            get {
                return ResourceManager.GetString("USEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם מלא.
        /// </summary>
        public static string USFullName {
            get {
                return ResourceManager.GetString("USFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ת.ז..
        /// </summary>
        public static string USIDCardNumber {
            get {
                return ResourceManager.GetString("USIDCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמא.
        /// </summary>
        public static string USPassword {
            get {
                return ResourceManager.GetString("USPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון.
        /// </summary>
        public static string USPhoneNumber {
            get {
                return ResourceManager.GetString("USPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפקיד.
        /// </summary>
        public static string USRoleID {
            get {
                return ResourceManager.GetString("USRoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטאטוס.
        /// </summary>
        public static string USStatusID {
            get {
                return ResourceManager.GetString("USStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחידה.
        /// </summary>
        public static string USUnitID {
            get {
                return ResourceManager.GetString("USUnitID", resourceCulture);
            }
        }
    }
}
