//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clusetrs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clusetrs()
        {
            this.SuppliersClusetrs = new HashSet<SuppliersClusetrs>();
            this.Tichurim = new HashSet<Tichurim>();
            this.Timchurim = new HashSet<Timchurim>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AuctionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<byte> DisplayNumber { get; set; }
        public Nullable<byte> SuppliersInTichur { get; set; }
        public string Name { get; set; }
    
        public virtual Auctions Auctions { get; set; }
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliersClusetrs> SuppliersClusetrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tichurim> Tichurim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timchurim> Timchurim { get; set; }
    }
}
