//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Clusters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clusters()
        {
            this.SuppliersClusters = new HashSet<SuppliersClusters>();
            this.Tichurim = new HashSet<Tichurim>();
            this.Timchurim = new HashSet<Timchurim>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "CLAuctionID", ResourceType = typeof(Resources.BasicAno))]
        public Nullable<int> AuctionID { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "CLStatusID", ResourceType = typeof(Resources.BasicAno))]
        public Nullable<int> StatusID { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Range(1, 999, ErrorMessageResourceName = "NotThrDig", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "CLDisplayNumber", ResourceType = typeof(Resources.BasicAno))]
        public Nullable<byte> DisplayNumber { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Range(1, Int64.MaxValue, ErrorMessageResourceName = "NotZEPDig", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "CLSuppliersInTichur", ResourceType = typeof(Resources.BasicAno))]
        public Nullable<byte> SuppliersInTichur { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "CLName", ResourceType = typeof(Resources.BasicAno))]
        public string Name { get; set; }

        public virtual Auctions Auctions { get; set; }
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliersClusters> SuppliersClusters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tichurim> Tichurim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timchurim> Timchurim { get; set; }
    }
}