//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimchurDatabaseEntities : DbContext
    {
        public TimchurDatabaseEntities()
            : base("name=TimchurDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auctions> Auctions { get; set; }
        public virtual DbSet<Clusetrs> Clusetrs { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<SuppliersClusetrs> SuppliersClusetrs { get; set; }
        public virtual DbSet<SuppliersTichurim> SuppliersTichurim { get; set; }
        public virtual DbSet<SuppliersTimchurim> SuppliersTimchurim { get; set; }
        public virtual DbSet<Tichurim> Tichurim { get; set; }
        public virtual DbSet<Timchurim> Timchurim { get; set; }
        public virtual DbSet<Units> Units { get; set; }
        public virtual DbSet<UnitsAuctions> UnitsAuctions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
