//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.SuppliersClusters = new HashSet<SuppliersClusters>();
            this.SuppliersTichurim = new HashSet<SuppliersTichurim>();
            this.SuppliersTimchurim = new HashSet<SuppliersTimchurim>();
        }
    
        public int ID { get; set; }
        public string CompanyNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Name { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliersClusters> SuppliersClusters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliersTichurim> SuppliersTichurim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliersTimchurim> SuppliersTimchurim { get; set; }
    }
}
