//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Tichurim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tichurim()
        {
            this.SuppliersTichurim = new HashSet<SuppliersTichurim>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string TichurNumber { get; set; }
        public Nullable<int> ClusterID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> DateTimeSelected { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public Nullable<int> UpdatedUserID { get; set; }
        public string UpdatedComment { get; set; }

        public virtual Clusters Clusters { get; set; }
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliersTichurim> SuppliersTichurim { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Units Units { get; set; }
    }
}