//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Database
{
    using Infrastructure;
  
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Tichurim = new HashSet<Tichurim>();
            this.Tichurim1 = new HashSet<Tichurim>();
            this.Timchurim = new HashSet<Timchurim>();
            this.Timchurim1 = new HashSet<Timchurim>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "USUnitID", ResourceType = typeof(Resources.BasicAno))]
        public Nullable<int> UnitID { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "USRoleID", ResourceType = typeof(Resources.BasicAno))]
        public Nullable<int> RoleID { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "USStatusID", ResourceType = typeof(Resources.BasicAno))]
        public Nullable<int> StatusID { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [RegularExpression("^[0-9]*$", ErrorMessageResourceName = "numberExpe", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [CustomIdErrorAttribu]
        [Display(Name = "USIDCardNumber", ResourceType = typeof(Resources.BasicAno))]
        public string IDCardNumber { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "USPhoneNumber", ResourceType = typeof(Resources.BasicAno))]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "USFullName", ResourceType = typeof(Resources.BasicAno))]
        public string FullName { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "USPassword", ResourceType = typeof(Resources.BasicAno))]
        public string Password { get; set; }
        [Required(ErrorMessageResourceName = "Required", ErrorMessageResourceType = typeof(Resources.BasicAno))]
        [Display(Name = "USEmail", ResourceType = typeof(Resources.BasicAno))]
        [EmailAddress(ErrorMessageResourceName = "InvalidEmail", ErrorMessageResourceType = typeof(Resources.BasicAno))]
     
        public string Email { get; set; }

        public virtual Roles Roles { get; set; }
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tichurim> Tichurim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tichurim> Tichurim1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timchurim> Timchurim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timchurim> Timchurim1 { get; set; }
        public virtual Units Units { get; set; }
    }
}
